sonata_admin:
    title: 'Ant'
    dashboard:
        blocks:
            - type: sonata.admin.block.admin_head
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            STAFF:    [EDIT, LIST]
            ADMIN:    [MASTER]
            EDITOR:   [EDIT, LIST, CREATE, DELETE]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
    templates:
        layout:  AntAdminBundle::standard_layout.html.twig
        ajax:    AntAdminBundle::ajax_layout.html.twig
        list:    AntAdminBundle:CRUD:list.html.twig
        show:    AntAdminBundle:CRUD:show.html.twig

        history: AntAdminBundle:CRUD:history.html.twig
        preview: AntAdminBundle/CRUD/preview.html.twig
        delete:  AntAdminBundle:CRUD:delete.html.twig
        batch:   AntAdminBundle:CRUD:list__batch.html.twig
        acl:     AntAdminBundle:CRUD:acl.html.twig
        action:  AntAdminBundle:CRUD:action.html.twig
        select:  AntAdminBundle:CRUD:list__select.html.twig
        dashboard:           AntAdminBundle:Core:dashboard.html.twig
        search:              AntAdminBundle:Core:search.html.twig
        batch_confirmation:  AntAdminBundle:CRUD:batch_confirmation.html.twig
        inner_list_row:      AntAdminBundle:CRUD:list_inner_row.html.twig
        base_list_field:     AntAdminBundle:CRUD:base_list_field.html.twig
        list_block:          AntAdminBundle:Block:block_admin_list.html.twig
        user_block:          AntAdminBundle:Core:user_block.html.twig
        pager_links:         AntAdminBundle:Pager:links.html.twig
        pager_results:       AntAdminBundle:Pager:results.html.twig
        history_revision_timestamp:  AntAdminBundle:CRUD:history_revision_timestamp.html.twig
        short_object_description:    AntAdminBundle:Helper:short-object-description.html.twig
        search_result_block: AntAdminBundle:Block:block_search_result.html.twig


sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.admin_head:
            contexts:   [admin]
        sonata.media.block.media:
            contexts:   [admin]

