twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
#    paths:
#        - '%kernel.project_dir%/../Ant/AdminBundle/Resources/views': ~

    form_themes:
            # other files
            - 'AntMediaBundle:Form:media_widgets.html.twig'
            - 'AntAdminBundle:Form:tinymce.html.twig'
