order_new:
    path:  /new
    defaults: { _controller: "AntWebBundle:OrderForm:new" }

order_create_front:
    path:  /create
    defaults: { _controller: "AntWebBundle:OrderForm:create" }
    requirements: { _method: post }
