sonata_media_gallery_index:
    path:  /
    defaults: { _controller: "AntMediaBundle:Gallery:index" }

sonata_media_gallery_view:
    path:  /{id}-{slug}
    defaults: { _controller: "AntMediaBundle:Gallery:view" }