<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Ant\MediaBundle\Entity;

use App\Entity\House;
use Sonata\MediaBundle\Entity\BaseGallery;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Gallery extends BaseGallery
{
//    /**
//     * @var House
//     *
//     * @ORM\OneToOne(targetEntity="App\Entity\House")
//     */
//    private $house;
//
//    /**
//     * @var House
//     *
//     * @ORM\OneToOne(targetEntity="App\Entity\House")
//     */
//    private $housePlan;

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var string $link
     *
     */
    private $link;

    /**
     * @var string $description
     *
     */
    protected $description;

    /**
     * @Gedmo\Slug(fields={"title"})
     *
     */
    protected $slug;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    public function setDescription($description){
        $this->description = $description;
        return $this;
    }


    /**
     * Get Description
     *
     * @return string $description
     */
    public function getDescription(){
        return $this->description;
    }


    public function setLink ($link) {
        $this->link = $link;
        return $this;
    }

    public function getLink(){
        return $this->link;
    }

    /**
     * Get slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }
//
//    /**
//     * @return House
//     */
//    public function getHouse(): House
//    {
//        return $this->house;
//    }
//
//    /**
//     * @param House $house
//     * @return Gallery
//     */
//    public function setHouse(House $house): Gallery
//    {
//        $this->house = $house;
//        return $this;
//    }
//
//    /**
//     * @return House
//     */
//    public function getHousePlan(): House
//    {
//        return $this->housePlan;
//    }
//
//    /**
//     * @param House $housePlan
//     * @return Gallery
//     */
//    public function setHousePlan(House $housePlan): Gallery
//    {
//        $this->housePlan = $housePlan;
//        return $this;
//    }


}
