# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
            resources:
                # other files
                - 'AntMediaBundle:Form:media_widgets.html.twig'
                - 'AntAdminBundle:Form:tinymce.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types: #this is about this line and line below
                    json:     Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

#Sonata Block

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.admin_head:
            contexts:   [admin]
        sonata.media.block.media:
            contexts:   [admin]


sonata_admin:
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            STAFF:    [EDIT, LIST]
            ADMIN:    [MASTER]
            EDITOR:   [EDIT, LIST, CREATE, DELETE]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
    dashboard:
        blocks:
            -
                type: sonata.admin.block.admin_head
    templates:
        layout:  AntAdminBundle::standard_layout.html.twig
        ajax:    AntAdminBundle::ajax_layout.html.twig
        list:    AntAdminBundle:CRUD:list.html.twig
        show:    AntAdminBundle:CRUD:show.html.twig

        history: AntAdminBundle:CRUD:history.html.twig
        preview: AntAdminBundle:CRUD:preview.html.twig
        delete:  AntAdminBundle:CRUD:delete.html.twig
        batch:   AntAdminBundle:CRUD:list__batch.html.twig
        acl:     AntAdminBundle:CRUD:acl.html.twig
        action:  AntAdminBundle:CRUD:action.html.twig
        select:  AntAdminBundle:CRUD:list__select.html.twig
        dashboard:           AntAdminBundle:Core:dashboard.html.twig
        search:              AntAdminBundle:Core:search.html.twig
        batch_confirmation:  AntAdminBundle:CRUD:batch_confirmation.html.twig
        inner_list_row:      AntAdminBundle:CRUD:list_inner_row.html.twig
        base_list_field:     AntAdminBundle:CRUD:base_list_field.html.twig
        list_block:          AntAdminBundle:Block:block_admin_list.html.twig
        user_block:          AntAdminBundle:Core:user_block.html.twig
        pager_links:         AntAdminBundle:Pager:links.html.twig
        pager_results:       AntAdminBundle:Pager:results.html.twig
        history_revision_timestamp:  AntAdminBundle:CRUD:history_revision_timestamp.html.twig
        short_object_description:    AntAdminBundle:Helper:short-object-description.html.twig
        search_result_block: AntAdminBundle:Block:block_search_result.html.twig

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Ant\UserBundle\Entity\User


stof_doctrine_extensions:
    default_locale: en
    translation_fallback: true
    orm:
        default:
            sluggable: true
            tree: true
            timestampable: true
            softdeleteable: true


knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: AntWebBundle::knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default



knp_paginator:
    page_range: 10                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: AntWebBundle::paginator_sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

liip_imagine:
    filter_sets:
        default_small:
            quality: 100
            controller_action: 'SonataMediaBundle:Media:liipImagineFilter'
            filters:
                thumbnail: { size: [100, 70], mode: outbound }
        default_big:
            quality: 75
            controller_action: 'SonataMediaBundle:Media:liipImagineFilter'
            filters:
                thumbnail: { size: [500, 300], mode: outbound }
        admin:
            quality: 75
            controller_action: 'SonataMediaBundle:Media:liipImagineFilter'
            filters:
                thumbnail: { size: [500, 300], mode: outbound }

gregwar_captcha: ~