Ant\WebBundle\Entity\Ad:
    properties:
        file:
            - File:
                maxSize: 6000000

#Ant\WebBundle\Entity\OrderForm:
#    properties:
#        name:
#            - NotBlank: ~
#        surname:
#            - NotBlank: ~
#        phone:
#            - NotBlank: ~
#        email:
#            - NotBlank: ~
#            - Email:
#        message:
#            - NotBlank: ~