<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Ant\MediaBundle\Entity;

use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Media extends BaseMedia
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var \Ant\WebBundle\Entity\News
     */
    private $news;

    /**
     * @var \Ant\WebBundle\Entity\Ad
     */
    private $ad;


//    protected $uploadFile;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set news
     *
     * @param \Ant\WebBundle\Entity\News $news
     *
     * @return Media
     */
    public function setNews($news = null)
    {
        $this->news = $news;

        return $this;
    }

    /**
     * Get news
     *
     * @return \Ant\WebBundle\Entity\News
     */
    public function getNews()
    {
        return $this->news;
    }

    /**
     * Set ad
     *
     * @param \Ant\WebBundle\Entity\Ad $ad
     *
     * @return Media
     */
    public function setAd($ad = null)
    {
        $this->ad = $ad;

        return $this;
    }

    /**
     * Get ad
     *
     * @return \Ant\WebBundle\Entity\Ad
     */
    public function getAd()
    {
        return $this->ad;
    }


//    public function preUpload()
//    {
//        if ($this->uploadFile) {
//            $this->path = sha1(uniqid()).'.'.$this->uploadFile->guessExtension();
//        }
//    }
}